### ISSUE TITLE
Column Bias Investigation

### ISSUE THREAD

**Issue by dinkelk** [DayStarEngineering/DataAnalysis#2]
Characterize the bias in our columns (plot of robust std vs robust mean)
Develop algorithm to remove this bias.

**Comment by ZachDischner** [comment]
I am doing it

**Comment by ZachDischner** [comment]
Done. First revision at least.

**Comment by dinkelk** [comment]
What did you find out / implement?

**Comment by ZachDischner** [comment]
Found some good stuff. Got a flatter background. I haven't implemented anything yet in the scripts, but its written and ready to test. Still a noisy image though. 

Need to adjust a few things, but its working. I can show you guys tomorrow/sometime.

**Comment by ZachDischner** [comment]
Also, the background went from distinctly non-normal to pretty normal looking. Seems good for you guys. I'll show you tomorrow.
